spring:
  application:
    name: discodeit

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50
    open-in-view: false # TODO: 디버깅모드 혹은 jconsole등 영속성컨텍스트/스레드 값 체크하여 실제 어느 스코프까지 가지고있는지 모니터링해볼것

  cloud:
    aws:
      credentials:
        accessKey: ${AWS_ACCESS_KEY_ID}
        secretKey: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_S3_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET}

  boot:
    admin:
      client:
        instance:
          name: discodeit

logging:
  level:
    root: info

discodeit:
  storage:
    local:
      root-path: ./storage    # 프로젝트 폴더 아래 storage 디렉토리
  repository:
    type: jcf
    file-directory: ./data

info:
  app:
    name: Discodeit
    version: 1.7.0

  runtime:
    java-version: 17
    spring-boot-version: 3.4.0

