spring:
  datasource:
    url: jdbc:h2:mem:sprint
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: never # schema.sql, data.sql 안 씀

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com.sprint.mission.discodeit: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

server:
  port: 8080