spring:
  application:
    name: discodeit

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
#        show_sql: true  # System.out 기반 출력
        format_sql: true
        default_batch_fetch_size: 50
    open-in-view: false # TODO: 디버깅모드 혹은 jconsole등 영속성컨텍스트/스레드 값 체크하여 실제 어느 스코프까지 가지고있는지 모니터링해볼것

logging:
  level:
    org.hibernate.SQL: debug  # spring logging 기반 출력
    org.hibernate.orm.jdbc.bind: trace   # 바인딩 값까지 보고 싶을 때

## 추후 아래 안쓰면 지울 것
discodeit:
  storage:
    type: local          # <= 여기 값이 'local'일 때만 LocalBinaryContentStorage를 빈으로 등록
    local:
      root-path: ./storage    # 프로젝트 폴더 아래 storage 디렉토리
  repository:
    type: jcf
    file-directory: ./data